apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: tekton-prune-test-run
spec:
  params:
    - name: ttl_label
      value: "tekton.dev/ttl"
    - name: no_execute
      value: "false"
    - name: object
      value: "pipelinerun"
    - name: namespace
      value: "kubeflow"
  serviceAccountName: tekton-object-role-sa
  taskRef:
    kind: Task
    name: tekton-prune
